[package]
name = "vitna-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
vitna-protocol.workspace = true
vitna-runner.workspace = true
vitna-policy.workspace = true
sha2.workspace = true